name: pkgdown

on:
  workflow_run:
    workflows: ["R-CMD-check-and-Coverage"]
    types: completed

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.

      - name: Build site
        run: Rscript -e 'pkgdown::build_site_github_pages(dest_dir = "docs", new_process = FALSE, install = FALSE)'

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          # Switch to gh-pages branch or create if it doesn't exist
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages